name: Build release zip

on:
  workflow_dispatch

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install SVN ( Subversion )
      run: |
        sudo apt-get update
        sudo apt-get install subversion

    - name: Generate zip
      uses: jordantrizz/action-wordpress-plugin-build-zip@develop
      env:
        SLUG: ecwid-shopping-cart

    - name: Output artifact URL
      run:  echo 'Artifact URL is ${{ steps.upload-plugin-artifact.outputs.artifact-url }}'
