name: Plugin asset/readme update
on:
  push:
    branches:
    - main
jobs:
  master:
    name: Push to Main
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'readme update')"
    environment: wordpress
    steps:
    - uses: actions/checkout@main
    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: protect-schemaorg-markup-in-html-editor
        IGNORE_OTHER_FILES: true