name: Plugin asset/readme update
on:
  push:
    branches:
    - master
jobs:
  master:
    name: Push to Master
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'readme update')"
    environment: wordpress
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install SVN ( Subversion )
      run: |
        sudo apt-get update
        sudo apt-get install subversion

    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: ecwid-shopping-cart
        IGNORE_OTHER_FILES: true